services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: reliquary-tower-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8888:5432
    volumes:
      - postgres_data:/var/lib/postgresql/reliquary-tower_data
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Adjust the port as needed for your Spring Boot app
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/reliquary-tower-db
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./server/logs:/app/logs
volumes:
  postgres_data:
    name: postgres_data
networks:
    postgres-db:
        driver: bridge