spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:8888/reliquary-tower-db
    username: postgres
    password: postgres
    hikari:
      initialization-fail-timeout: 15000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": false
        type:
          "[json_format_mapper]": jackson
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      introspection:
        enabled: true
logging:
  level:
    root: INFO                             # Default fallback for libraries
    "[org.eqdev.server]": DEBUG                # Show your detailed app logs
    "[org.springframework.orm.jpa]": WARN      # Hide noisy JPA lifecycle details
    "[org.hibernate.SQL]": WARN                # Don't flood the console with raw SQL queries unless debugging DB issues